server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/redis_cache
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  cache:
#    redis:
#      time-to-live: 20S
